from tkinter import *
import os.path
scr=Tk()
scr.title("NATIONAL BANK OF INDIA")
l10=Label(scr,text="OPEN ACCOUNT/NEW ACCOUNT",bg="red",fg="white",font=('time','20','bold'))
l10.place(x=230,y=5)
l=Label(scr,text="Enter full name",bg="blue",fg="white",font=('time','20','bold'))
l.place(x=10,y=55)
l1=Label(scr,text="Enter date of birth(00000000)",bg="blue",fg="white",font=('time','20','bold'))
l1.place(x=10,y=105)
l2=Label(scr,text="Enter phone number",bg="blue",fg="white",font=('time','20','bold'))
l2.place(x=10,y=155)
l3=Label(scr,text="Enter adhar number",bg="blue",fg="white",font=('time','20','bold'))
l3.place(x=10,y=205)
l4=Label(scr,text="Enter pancard number",bg="blue",fg="white",font=('time','20','bold'))
l4.place(x=10,y=255)
l5=Label(scr,text="Enter type of account('S' or 'R') ",bg="blue",fg="white",font=('time','20','bold'))
l5.place(x=10,y=305)
l6=Label(scr,text="Enter your first deposit",bg="blue",fg="white",font=('time','20','bold'))
l6.place(x=10,y=355)
e=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e.place(x=500,y=55)
e1=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e1.place(x=500,y=105)
e2=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e2.place(x=500,y=155)
e3=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e3.place(x=500,y=205)
e4=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e4.place(x=500,y=255)
e5=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e5.place(x=500,y=305)
e6=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e6.place(x=500,y=355)
b=Button(scr,text="SAVE",bg="orange",fg="black",bd=8,command=lambda:Save())
b.config(font=('Time','15','bold'))
b.place(x=350,y=405)
    

def Save():
    a=e3.get()
    a1=e.get()
    a2=e1.get()
    a3=e2.get()
    a4=e4.get()
    a5=e5.get()
    a6=e6.get()
    completeName = os.path.join("D:\\Bank",a+".txt")
    file1 = open(completeName, "w")
    file1.write(a1)
    file1.write("\t")
    file1.write("\nDATE OF BIRTH ")
    file1.write(a2)
    file1.write("\nPHONE NUMBER ")
    file1.write(a3)
    file1.write("\nADHAR CARD NUMBER ")
    file1.write(a)
    file1.write("\nPANCARD NUMBER ")
    file1.write(a4)
    file1.write("\nACCOUNT TYPE ")
    file1.write(a5)
    file1.close()
    completeName = os.path.join("D:\\Bank",a4+".txt")
    file2 = open(completeName, "w")
    file2.write(a6)
    file2.close()

l7=Label(scr,text="Enter adhar number",bg="blue",fg="white",font=('time','20','bold'))
l7.place(x=10,y=570)
e7=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e7.place(x=500,y=570)
l8=Label(scr,text="Enter pancard number",bg="blue",fg="white",font=('time','20','bold'))
l8.place(x=10,y=630)
l9=Label(scr,text="MY DETAILS/CHECK BALANCE",bg="red",fg="white",font=('time','20','bold'))
l9.place(x=230,y=500)
e8=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e8.place(x=500,y=630)
b1=Button(scr,text="SHOW",bg="orange",fg="black",bd=8,command=lambda:account())
b1.config(font=('Time','15','bold'))
b1.place(x=350,y=700) 


def account():
    scr0=Tk()
    scr0.title("ACCOUNT DETAIL")
    b=e7.get()
    b1=e8.get()
    completeName = os.path.join("D:\\Bank",b+".txt")
    file1 = open(completeName, "r")
    det=file1.read()
    l1=Label(scr0,text=det,bg="pink",fg="black",font=('time','20','bold'))
    l1.place(x=50,y=100)
    file1.seek(0)
    completeName1 = os.path.join("D:\\Bank",b1+".txt")
    file2 = open(completeName1, "r")
    z="Your current balance is RS.  "
    det1=z+file2.read()
    l2=Label(scr0,text=det1,bg="blue",fg="black",font=('time','20','bold'))
    l2.place(x=100,y=400)
    file2.seek(0)  
e10=Entry(scr,bg="powder blue",fg="black",font=('Time','46','bold'))
e10.place(x=850,y=159)
b3=Button(scr,text="1",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(1))
b3.config(font=('Time','15','bold'))
b3.place(x=850,y=236)
b4=Button(scr,text="2",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(2))
b4.config(font=('Time','15','bold'))
b4.place(x=1080,y=236)
b5=Button(scr,text="3",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(3))
b5.config(font=('Time','15','bold'))
b5.place(x=1310,y=236)
b6=Button(scr,text="4",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(4))
b6.config(font=('Time','15','bold'))
b6.place(x=850,y=313)
b7=Button(scr,text="5",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(5))
b7.config(font=('Time','15','bold'))
b7.place(x=1080,y=313)
b8=Button(scr,text="6",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(6))
b8.config(font=('Time','15','bold'))
b8.place(x=1310,y=313)   
b9=Button(scr,text="7",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(7))
b9.config(font=('Time','15','bold'))
b9.place(x=850,y=390)
b10=Button(scr,text="8",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(8))
b10.config(font=('Time','15','bold'))
b10.place(x=1080,y=390)
b11=Button(scr,text="9",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(9))
b11.config(font=('Time','15','bold'))
b11.place(x=1310,y=390)
b12=Button(scr,text=".",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick("."))
b12.config(font=('Time','15','bold'))
b12.place(x=850,y=467)
b13=Button(scr,text="0",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:btnClick(0))
b13.config(font=('Time','15','bold'))
b13.place(x=1080,y=467)
b14=Button(scr,text="C",bg="powder blue",fg="black",bd=8,padx=95,pady=10,command=lambda:clrBtn())
b14.config(font=('Time','15','bold'))
b14.place(x=1310,y=467)
b15=Button(scr,text="CREDITED",bg="powder blue",fg="black",bd=8,padx=280,pady=10,command=lambda:credited())
b15.config(font=('Time','15','bold'))
b15.place(x=850,y=544)
b15=Button(scr,text="DEBITED",bg="powder blue",fg="black",bd=8,padx=286,pady=10,command=lambda:debited())
b15.config(font=('Time','15','bold'))
b15.place(x=850,y=621)
l11=Label(scr,text="UPDATE BALANCE",bg="red",fg="white",font=('time','20','bold'))
l11.place(x=1000,y=5)
l11=Label(scr,text="Enter pancard number",bg="blue",fg="white",font=('time','20','bold'))
l11.place(x=850,y=82)
e12=Entry(scr,bg="grey",fg="black",font=('Time','20','bold'))
e12.place(x=1230,y=82)


def btnClick(n):
    global operator
    operator=""
    operator=operator+str(n)
    e10.insert(100,operator)

def clrBtn():
    e10.delete(len(e10.get())-1)

def credited():
    b=e12.get()
    completeName = os.path.join("D:\\Bank",b+".txt")
    file= open(completeName, "r")
    det=file.read()
    file.seek(0)
    b1=e10.get()
    credit=int(b1)+int(det)
    disp="New balance is RS. "+str(credit)
    l12=Label(scr,text=disp,bg="white",fg="black",font=('time','20','bold'))
    l12.place(x=850,y=695)
    completeName1 = os.path.join("D:\\Bank",b+".txt")
    r=file.read().replace(str(det),str(credit))
    file1= open(completeName1, "w")
    file1.write(r)
    file1.close()


def debited():
    error="LOW CREDIT"
    b=e12.get()
    completeName = os.path.join("D:\\Bank",b+".txt")
    file= open(completeName, "r")
    det=file.read()
    file.seek(0)
    b1=e10.get()
    debit=int(det)-int(b1)
    if(debit>=0):
        disp="New balance is RS. "+str(debit)
        l12=Label(scr,text=disp,bg="white",fg="black",font=('time','20','bold'))
        l12.place(x=850,y=695)
        completeName1 = os.path.join("D:\\Bank",b+".txt")
        r=file.read().replace(str(det),str(debit))
        file1= open(completeName1, "w")
        file1.write(r)
        file1.close()
    else:
        e10.delete(0,END)
        e10.insert(0,str(error))

l20=Label(scr,text="CREATED BY YASH DIXIT",bg="white",fg="black",font=('time','20','bold'))
l20.place(x=1100,y=755)
l30=Label(scr,text="For any enquiry visit www.nbi.gov.in ",bg="white",fg="black",font=('time','20','bold'))
l30.place(x=200,y=755)    
